### ISSUE TITLE
AWS->Azure pattern use of cognito GetOpenIdTokenForDeveloperIdentity 

### ISSUE THREAD

**Issue by liwadman** [clutchsecurity/federator#1]
GetOpenIdTokenForDeveloperIdentity API is intended for back ends or developers to request tokens on behalf of users. There is no control on this API for restricting which identities a token can be requested for - meaning if you enable this API for different roles in your account, they can all restrict tokens with arbitrary sub (subject) claim's for the different identities in a pool.

Using this for a machine to machine/cloud to cloud auth solution requires consideration and controls put in place by other means than IAM policy to restrict which IAM principals get what tokens that represent what identities.

To put it to an example, suppose you have two ec2 instances in the account, with a different role/instance profile, but both have access to call GetOpenIdTokenForDeveloperIdentity. Both instances could request a token with a subject claim that was intended to represent the other.

**Comment by AXsagi** [comment]
Hi @liwadman,

Thank you for your input on this matter!

While researching how to implement federation between AWS and Azure, we encountered the issue you mentioned. Unfortunately, AWS Cognito doesn't offer an option to limit access to specific instances.

It's important for users of this federation to be aware that any EC2 instance (or other service) with a role that doesn't restrict access to a specific identity pool (via ResourceTags or similar mechanisms) will have access to all identity pools in Cognito. It is the user's responsibility to properly manage the IAM policies attached to resources with access to Cognito to ensure they limit access to only the required identity pools.

We'll include a bold disclaimer in both the README.md and the Terraform file to ensure users are fully informed about this.

**Comment by liwadman** [comment]
I think the ideal messaging would be to tell people up front that the trusted thing here is the identity pool, not a user/subject within an identity pool. Someone who tries to follow this pattern who making assumptions that there is some mapping between IAM principals and cognito token sub's is setting themselves up for a bad day.

**Comment by AXsagi** [comment]
Hi @liwadman,

I've [added](https://github.com/clutchsecurity/federator/commit/477be9f2313eea1920896744a99d13af555e2869) a disclaimer addressing the issue in both the Terraform file and the README.md.

Thanks again for your valuable input on the matter!
